language: python
python:
  - "3.6"
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - FLASK_SECRET_KEY=dumbkey
# command to install dependencies
install: make setup
# # command to run tests
script: make test
notifications:
  email: false
